export { default as AuthController } from "./AuthController.js"
export { default as PostsController } from "./PostsController.js"
export { default as UploadsController } from "./UploadsController.js"
export { default as ProductsController } from "./ProductsController.js"
export { default as CommentsController } from "./CommentsController.js"
export { default as UsersController } from "./UsersController.js"
