export { default as UserController } from "./UserController.js"
export { default as PostController } from "./PostController.js"
export { default as UploadsController } from "./UploadsController.js"
export { default as ProductsController } from "./ProductsController.js"
export { default as CommentsController } from "./CommentsController.js"
